# Generated by Django 4.1.2 on 2022-11-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_chapter_chaptermain_delete_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
