# Generated by Django 4.1.2 on 2022-11-02 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_chapter_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='articles',
        ),
    ]
