# Generated by Django 4.1.2 on 2022-11-02 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_scope_rename_chapter_tag_delete_chaptermain_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
