# Generated by Django 4.1.2 on 2022-11-02 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_scope_is_main_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='chapter',
        ),
        migrations.AddField(
            model_name='scope',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='articles.tag', verbose_name='РАЗДЕЛ'),
            preserve_default=False,
        ),
    ]
